services:
  multimodal-adapter:
    container_name: nacho-bot-multimodal-adapter
    build:
      context: .
      dockerfile: dockerfile
      additional_contexts:
        nachobot: ../NachoBot
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8070:8070"
    volumes:
      - ./configs:/workspace/NachoBot-Multimodal-Adapter/configs
      - ./models:/workspace/NachoBot-Multimodal-Adapter/models
      - ./logs:/workspace/NachoBot-Multimodal-Adapter/logs
    restart: always
    networks:
      - nacho_bot

networks:
  nacho_bot:
    external: true
