[project]
name = "NachoBotMultimodalAdapter"
version = "0.3.1"
description = "A multimodal TTS, ASR, and VLM adapter for NachoBot"
requires-python = ">=3.11,<3.13"
dependencies = [
    "aiohttp>=3.14.0",
    "base64io>=1.0.3",
    "cryptography>=48.0.1",
    "einops>=0.8.2",
    "fastapi>=0.140.13",
    "funasr>=1.3.1",
    "loguru>=0.7.3",
    "modelscope>=1.34.0",
    "numba>=0.65.0",
    "numpy",
    "openai>=2.26.0",
    "pillow>=12.1.1",
    "pydantic>=2.12.5",
    "pydub>=0.25.1",
    "python-multipart>=0.0.27",
    "pyyaml>=6.0",
    "requests>=2.31.0",
    "scipy>=1.17.1",
    "soundfile>=0.12.1",
    "timm>=1.0.25",
    "toml>=0.10.2",
    "torch",
    "torchaudio",
    "torchvision",
    "transformers==4.51.3",
    "uvicorn>=0.41.0",
    "websockets>=12.0",
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchaudio = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }

[tool.ruff]

include = ["*.py"]

# 行长度设置
line-length = 120

[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []

# 启用的规则
select = [
    "E", # pycodestyle 错误
    "F", # pyflakes
    "B", # flake8-bugbear
]

ignore = ["E711","E501"]

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"


# 使用双引号表示字符串
quote-style = "double"

# 尊重魔法尾随逗号
# 例如：
# items = [
#     "apple",
#     "banana",
#     "cherry",
# ]
skip-magic-trailing-comma = false

# 自动检测合适的换行符
line-ending = "auto"
