services:
  koishi-adapter:
    container_name: nacho-bot-koishi-adapter
    build:
      context: .
      additional_contexts:
        nachobot: ../NachoBot
    environment:
      - TZ=Asia/Shanghai
      - NACHOBOT_CORE_TOKEN=${NACHOBOT_CORE_TOKEN:-}
      - NACHOBOT_FFMPEG_DIR=/usr/bin
    volumes:
      - ./config.toml:/workspace/NachoBot-Koishi-Adapter/config.toml
      - ../NachoBot/config:/workspace/NachoBot/config:ro
    restart: always
    networks:
      - nacho_bot

networks:
  nacho_bot:
    external: true
