services:
  discord-adapter:
    container_name: nacho-bot-discord-adapter
    build:
      context: .
      additional_contexts:
        nachobot: ../NachoBot
    environment:
      - TZ=Asia/Shanghai
      - NACHOBOT_CORE_TOKEN=${NACHOBOT_CORE_TOKEN:-}
      - NACHOBOT_CORE_HOST=core
      - NACHOBOT_CORE_PORT=8000
    volumes:
      - ./config.toml:/workspace/NachoBot-DiscordVC-Adapter/config.toml
      - ../NachoBot/config:/workspace/NachoBot/config:ro
    restart: always
    networks:
      - nacho_bot

networks:
  nacho_bot:
    external: true
