services:
  discord-adapter:
    container_name: nacho-bot-discord-adapter
    build:
      context: .
      additional_contexts:
        multimodal: ../NachoBot-Multimodal-Adapter
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.toml:/discord-adapter/config.toml  # 配置文件
    restart: always
    networks:
      - nacho_bot

networks:
  nacho_bot:
    external: true
