services:
  discord-adapter:
    container_name: nacho-bot-discord-adapter
    build:
      context: .
      additional_contexts:
        nachobot: ../NachoBot
        multimodal: ../NachoBot-Multimodal-Adapter
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.toml:/workspace/NachoBot-DiscordVC-Adapter/config.toml
      - ../NachoBot/config:/workspace/NachoBot/config:ro
      - ../NachoBot-Multimodal-Adapter/configs:/workspace/NachoBot-Multimodal-Adapter/configs:ro
      - ../NachoBot-Multimodal-Adapter/models:/workspace/NachoBot-Multimodal-Adapter/models
    restart: always
    networks:
      - nacho_bot

networks:
  nacho_bot:
    external: true
