FROM python:3.13-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# 设置工作目录
WORKDIR /nachobot_tts_adapter

# 安装本地 ncnk_message 包
COPY ncnk_message /ncnk_message
RUN uv pip install --system -e /ncnk_message

# 安装依赖
COPY requirements.txt pyproject.toml ./
RUN uv pip install --system --upgrade pip
RUN uv pip install --system -r requirements.txt

# 复制项目代码
COPY . .

# 创建配置目录并从模板复制默认配置
RUN mkdir -p /nachobot_tts_adapter/configs && \
    cp /nachobot_tts_adapter/template_configs/base_template.toml /nachobot_tts_adapter/configs/base.toml && \
    cp /nachobot_tts_adapter/template_configs/gpt-sovits_template.toml /nachobot_tts_adapter/configs/gpt-sovits.toml

# 暴露端口
EXPOSE 8070

# 定义可以被映射的卷
VOLUME ["/nachobot_tts_adapter/configs"]

# 运行应用
CMD ["python", "main.py"]
