# 使用前请先创建外部网络: docker network create nacho_bot
services:
  adapters:
    container_name: nacho-bot-adapters
    image: unclas/nachobot-adapter:latest
    environment:
      - TZ=Asia/Shanghai
#    ports:
#      - "8095:8095"
    volumes:
      - ./docker-config/adapters/config.toml:/adapters/config.toml # 持久化adapters配置文件
      - ./data/adapters:/adapters/data # adapters 数据持久化
    restart: always
    networks:
      - nacho_bot
  core:
    container_name: nacho-bot-core
    build:
      context: .
      dockerfile: Dockerfile
    image: nachobot-core:local
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./docker-config/mmc/.env:/NachoBot/.env # 持久化env配置文件
      - ./docker-config/mmc:/NachoBot/config # 持久化bot配置文件
      - ./data/NachoBot/Nachobot_statistics.html:/NachoBot/Nachobot_statistics.html #统计数据输出
      - ./data/NachoBot:/NachoBot/data # 共享目录
      - ./data/NachoBot/plugins:/NachoBot/plugins # 插件目录
      - ./data/NachoBot/logs:/NachoBot/logs # 日志目录
    restart: always
    networks:
      - nacho_bot
  napcat:
    environment:
      - NAPCAT_UID=1000
      - NAPCAT_GID=1000
      - TZ=Asia/Shanghai
    ports:
      - "6099:6099"
    volumes:
      - ./docker-config/napcat:/app/napcat/config # 持久化napcat配置文件
      - ./data/qq:/app/.config/QQ # 持久化QQ本体
      - ./data/NachoBot:/NachoBot/data # 共享目录
    container_name: nacho-bot-napcat
    restart: always
    image: mlikiowa/napcat-docker:latest
    networks:
      - nacho_bot
  sqlite-web:
    # 注意：coleifer/sqlite-web 镜像不支持arm64
    image: coleifer/sqlite-web
    container_name: sqlite-web
    restart: always
    ports:
      - "8120:8080"
    volumes:
      - ./data/NachoBot:/data/NachoBot
    environment:
      - SQLITE_DATABASE=NachoBot/NachoBot.db  # 你的数据库文件
    networks:
      - nacho_bot

  # chat2db占用相对较高但是功能强大
  # 内存占用约600m，内存充足推荐选此
  # chat2db:
  #   image: chat2db/chat2db:latest
  #   container_name: nacho-bot-chat2db
  #   restart: always
  #   ports:
  #     - "10824:10824"
  #   volumes:
  #     - ./data/nachoBot:/data/nachoBot
  #   networks:
  #     - nacho_bot
  
networks:
  nacho_bot:
    external: true
