services:
  bilibili-adapter:
    container_name: nacho-bot-bilibili-adapter
    build:
      context: .
      additional_contexts:
        nachobot: ../NachoBot
        multimodal: ../NachoBot-Multimodal-Adapter
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.toml:/workspace/NachoBot-Bilibili-Adapter/config.toml
      - ../NachoBot/config:/workspace/NachoBot/config:ro
      - ../NachoBot-Multimodal-Adapter/configs:/workspace/NachoBot-Multimodal-Adapter/configs:ro
      - ../NachoBot-Multimodal-Adapter/models:/workspace/NachoBot-Multimodal-Adapter/models
      - ./proxy.json:/workspace/NachoBot-Bilibili-Adapter/proxy.json
      - ./idle_texts.json:/workspace/NachoBot-Bilibili-Adapter/idle_texts.json
      - ./subtitles.txt:/workspace/NachoBot-Bilibili-Adapter/subtitles.txt
      - ./subtitles1.txt:/workspace/NachoBot-Bilibili-Adapter/subtitles1.txt
      - ./logs:/workspace/NachoBot-Bilibili-Adapter/logs
    restart: always
    networks:
      - nacho_bot

networks:
  nacho_bot:
    external: true
